name: Build elasticsearch

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: 7.16.1
        description: Elasticsearch version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/techiall/elasticsearch:${{ github.event.inputs.version }}
          build-args:
            ES_VERSION=${{ github.event.inputs.version }}
